language: ruby
rvm:
  - 2.5.1
postgres:
  adapter: postgresql
  database: hiking_app_test
  username: hikingapp
script:
  - export RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: "25b0cb76-bf7b-4a0e-a0bf-25d1deb6c3d9"
  on: master
  app: hiking-app